
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: journeybeacon
    author: Miki
    version: '@project.version@'
spring:
  profiles:
    active: dev